<div id="view-content">
	<h3><?php if(isset($this->page)) echo "Update Page"; else echo"New Page"?></h3>
	<form method="post">
		<div class="form-group">
		  <label for="title">Title: </label>
		  <input type="text" class="form-control" name="title" value="<?php if(isset($this->page)) echo $this->page['title'];?>">
		</div>
<br>
		<div class="form-group">
		  <label for="content">Content: </label>
		 <textarea name="content" rows="8" cols="80" value="<?php if(isset($this->page)) echo $this->page['content'];?>"></textarea>
		</div>
<br>
		<input type="submit" value="<?php if(isset($this->page)) echo "update page"; else echo"create page"?>">

	</form>
</div>
	<h3><?php if(isset($this->error)) echo $this->error ;?></h3>
