<?php if($this->permession==0) { ?>
	<h1>you don't have permession to access this page</h1>

<?php } else { ?>
<div id="view-content">

<div class="container-fluid">
	<div class="text-center">
		<h3>List All Pages</h3>	
	</div>
	<div class="row">
		<div class="col-sm-8 push-sm-2">
			<table class="table">
			<thead>
				<tr>
					<th>Title</th>
					<th>Content</th>
					<th colspan="2">actions</th>
				</tr>
			</thead>
			<tbody>
						<?php foreach ($this->pages as $page) { ?>
		<tr>
		<td><?= $page['title']?></td>
		<td><?= $page['content']?></td>
		<td><a href="/pages/edit/p_id/<?=$page['p_id']?>">update</a></td>
		<td><a href="/pages/delete/p_id/<?=$page['p_id']?>">delete</a></td>
		</tr>
		<?php } ?>
			</tbody>
			</table>			
		</div>
	</div>
</div>
	<div class="text-center">
		<a class="btn btn-primary btn-outline-primary" href="/pages/add">new page</a>
	</div>
		 <?= $this->paginationControl($this->pages, 'Sliding', 'pagination.phtml'); ?>
</div>
<?php } ?>
