<style>
    a:link,
    a:visited
    {
        color: white;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
        margin: 5px auto;
    }

    div#more-information
    {
        b  background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Welcome to our <span id="zf-name">Company Website</span></h1>

    <h3>This is your project's main page</h3>

    <div id="more-information">
        <p>
            Main Sections: <br />
          <h3><a href="user/index">users</a> |
             <a href="pages/index">pages</a>|
              <a href="news/index">news</a>
              | <a href="settings/index">settings</a></h3>
        </p>
      <h3><a href="<?=$this->url(array('controller'=>'user','action'=>'logout'))?>">log out</a></h3>  
    </div>
</div>
