<div id="view-content">
	<h3>Login</h3>
	<form method="post" action="/Index/login">
		<div class="form-group">
		  <label for="username">User Name: </label>
		  <input type="text"  class="form-control" name="username" >
		</div>
<br>
		<div class="form-group">
		  <label for="password">Password: </label>
		 <input type="password"  class="form-control" name="password" >
		</div>
<br>
		<input type="submit" value="Login">

	</form>
</div>
	<h3><?php if(isset($this->error)) echo $this->error ;?></h3>
