<div id="view-content">
	<div class="container-fluid">
	<pre>
	


	
	</pre>
		<div class="row">
			<div class="col-sm-4 push-sm-4">
				<form class="form-signin" action="/Index/login" method="POST">
        	<h2 class="form-signin-heading">Please sign in</h2>
        	<label for="username" class="sr-only">Email address</label>
        	<input type="text" id="username" name="username" class="form-control" placeholder="Name" required="" autofocus="">
        	<label for="password" class="sr-only">Password</label>
        	<input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required="">
        	<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
				</form>				
			</div>
		</div>
	</div>
</div>
	<h3><?php if(isset($this->error)) echo $this->error ;?></h3>

