        <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">My Company</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/user/index">Users</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/pages/index">Pages</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/news/index">News</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/settings/index">Settings</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" method="get" action="<?=$this->url(array('controller'=>'user','action'=>'logout'))?>">
      <button class="btn btn-danger btn-outline-danger my-2 my-sm-0" type="submit">Log Out</button>
    </form>
  </div>
</nav>