<div id="view-content">
	<h3> "Update Settings"</h3>
	<form method="post">
		<div class="form-group">
		  <label for="admin_email">admin mail: </label>
		  <input type="text" class="form-control" name="admin_email" value="<?php echo $this->setting['admin_email'];?>">
		</div>
<br>
<div class="form-group">
	<label for="site_name">Site name: </label>
	<input type="text" class="form-control" name="site_name" value="<?php echo $this->setting['site_name'];?>">
</div>
<br>
<div class="form-group">
	<label for="phone">phone: </label>
	<input type="text" class="form-control" name="phone" value="<?php echo $this->setting['phone'];?>">
</div>
<div class="form-group">
	<label for="facebook_link">facebook: </label>
	<input type="text" class="form-control" name="facebook_link" value="<?php echo $this->setting['facebook_link'];?>">
</div>
<div class="form-group">
	<label for="twitter_link">twitter: </label>
	<input type="text" class="form-control" name="twitter_link" value="<?php echo $this->setting['twitter_link'];?>">
</div>
		<input type="submit" value="update">

	</form>
</div>
	<h3><?php if(isset($this->error)) echo $this->error ;?></h3>
