<?php if($this->permession==0) { ?>
	<h1>you don't have permession to access this page</h1>

<?php } else { ?>
<div id="view-content">
<br>
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-6 push-sm-3">
			<div class="card">
	<div class="card-header">
			<h3>Settings</h3>		
	</div>
	<div class="card-block">
		<ul>
	<?php foreach ($this->settings as $set) { ?>
	<tr>
	<li><h4>Admin Email:</h4> <?= $set['admin_email']?></li>
	<li><h4>Site Name:</h4> <?= $set['site_name']?></li>
	<li><h4>Phone:</h4> <?= $set['phone']?></li>
	<li><h4>facebook:</h4> <?= $set['facebook_link']?></li>
	<li><h4>twitter:</h4> <?= $set['twitter_link']?></li>
	<a class="btn btn-primary" href="/settings/edit">update</a>
	<?php } ?>
	</ul>		
	</div>
</div>
		</div>
	</div>
</div>

</div>
<?php } ?>


<div class="container-fluid">
	<div class="row">
		<div class="col-sm-6 push-sm-3">
			
		</div>
	</div>
</div>
