<br /><br />
<div id="view-content">
	<h3>New User</h3>
	<form class="" action="<?= $this->baseUrl()."/user/create" ?>" method="post">
		<div class="form-group">
		  <label for="">Name: </label>
		  <input type="text" class="form-control" name="username" value="<?php if (isset($this->user)) echo $this->user['username'];?>">
		</div>

		<div class="form-group">
		  <label for="">Password: </label>
		  <input type="password" class="form-control" name="password" value="<?php if (isset($this->user)) echo $this->user['password'];?>">
		</div>

	  <div class="form-group">
	    <label for="access_pages">can access pages: </label>
	    <input type="checkbox" class="form-control" name="access_pages">
	  </div>
		<div class="form-group">
			<label for="access_news">can access news: </label>
			<input type="checkbox" class="form-control" name="access_news">
		</div>
		<div class="form-group">
			<label for="access_users">can access users? </label>
			<input type="checkbox" class="form-control" name="access_users">
		</div>
		<div class="form-group">
			<label for="access_settings"> can access settings? </label>
			<input type="checkbox" class="form-control" name="access_settings">
		</div>

		<input type="submit" name="" value="create">

	</form>
</div>
