<?php if($this->permession==0) { ?>
	<h1>you don't have permession to access this page</h1>

<?php } else { ?>
<div id="view-content">
	<h3>List All Users</h3>
	<table>
		<tr>
		<th>id</th>
		<th>User Name</th>
		<th colspan="2">actions</th>
		</tr>
		<?php foreach ($this->users as $user) { ?>
		<tr>
		<td><?= $user['user_id']?></td>
		<td><?= $user['username']?></td>
		<td><a href="./edit/user_id/<?=$user['user_id']?>">update</a></td>
		<td><a href="./delete/user_id/<?=$user['user_id']?>">delete</a></td>
		</tr>
		<?php } ?>
	</table>
	<br>
<a href="./add">new user</a>
</div>
<?php } ?>
<h3><a href="<?=$this->url(array('controller'=>'user','action'=>'logout'))?>">log out</a></h3>  
